apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080  # NodePort 범위 내의 포트 번호
    - name: https
      port: 443
      targetPort: https
      nodePort: 30443  # NodePort 범위 내의 포트 번호
  selector:
    app.kubernetes.io/name: ingress-nginx