apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api-deployment
  namespace: basic-api
  labels:
    app: test-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-api
  template:
    metadata:
      labels:
        app: test-api
    spec:
      containers:
        - name: test-api
          image: kimjypar/test-api:dev-tag
          ports:
            - containerPort: 8000
              name: test-api
          env:
            - name: DB_URL
              value: "mysql+aiomysql://localhost:3306/test-db"
            - name: ENV
              value: prod